In [1]:
import os
import pandas as pd
import numpy as np

In [83]:
basedir = "C:\\Users\\ASABUNCUOGLU13\\Documents\\data\\vol02\\karton-slices-berk\\face-features\\"
scoresdir = "../scores/karton-group/"
input_file = "features.tsv"
label_file = "label.tsv"

In [84]:
#df = pd.read_csv(os.path.join(basedir % 0, input_file % 0))
df = pd.read_csv(os.path.join(basedir, input_file), sep="\t")
label = pd.read_csv(os.path.join(basedir, label_file), sep="\t")

In [85]:
df.head()

,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,gaze_angle_x,gaze_angle_y,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,0.98,1,0.108969,0.087301,-0.990204,-0.277103,0.114178,-0.954032,-0.086,0.103,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
1,0.98,1,0.301698,0.197916,-0.932635,0.070624,0.134092,-0.988449,0.191,0.171,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0
2,0.98,1,0.062991,0.175859,-0.982398,-0.208562,0.212141,-0.954724,-0.075,0.198,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.88,1,0.113977,0.208925,-0.971267,-0.132446,0.183577,-0.974042,-0.009,0.199,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.88,1,0.115142,0.301177,-0.946591,-0.118223,0.217745,-0.968819,-0.002,0.265,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [86]:
au_index = df.loc[np.logical_and(df[' AU01_c'] == 1.0, df[' AU04_c'] == 1.0, df[' AU12_c'] == 1.0)].index

In [87]:
label.loc[au_index].value_counts()

berk
2       37
dtype: int64

## AU Analysis

**boredom**
```
operation: np.logical_and(df[' AU01_c'] == 1.0, df[' AU04_c'] == 1.0, df[' AU12_c'] == 1.0)
video: touch designer

yagmur
 2        236
 1         10
 0         48
-1          5
-2          9


cansu
 2    463
 1    108
 0     34
-1     24
-2     84

berk
 2      139
 1       53
 0      104
-1        1

video: karton

yagmur
2         57

cansu
1       4

berk
2       37

```

**delight**
```
operation: np.logical_and(df[' AU25_c'] == 1.0, df[' AU26_c'] == 1.0) 
video: touch designer

yagmur
 2        226
 0         34
 1         24
-1         10
-2          2


cansu
 2    215
 1     57
 0     56
-1     15
-2     70

berk
 2      33
 0       3
-1       1

video: karton

yagmur
2         43

cansu
2        89
1         7

berk
 2      148
-1       19
 0        7

```

**confusion**
```
operation: np.logical_and(df[' AU02_c'] == 1.0, df[' AU07_c'] == 1.0, df[' AU14_c'] == 1.0)
video: touch designer

yagmur
2         45
1         15
0         10

cansu
-2    1

berk
2       20
1       11
0        6


video: karton

yagmur
2         26

cansu
2        4

berk
2       10

```